POST https://vndreamers-dev.herokuapp.com/auth/login
Content-Type: application/json


{
  "email": "devteam@vndreamers.com",
  "password": "@dev1234"
}

###

POST https://vndreamers-dev.herokuapp.com/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZXZ0ZWFtIiwiaWF0IjoxNTk2MDEzMTgyLCJleHAiOjE1OTYwOTk1ODJ9.NzE-4u9ai3kZIRVCJWvhjJxz9BSFcA1SVuCmUrOHJlXtIKOlbI79FrCkehdnbkLblXfK49G9W8ejKtxWivQZ_A

{
  "content": "dummy_first_name2",
  "status": 2
}


